<?php

/* @var \Puga\Action\Block\Action\View\Action $block */


$_productCollection = $block->getProductLoad();
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);

$wight = '300px';
$height = '300px';
$pos = $block->getPositioned();
$_helperAction = $this->helper(Puga\Action\Helper\Data::class);

?>

<h2><?= $block->getName(); ?></h2>
<?php // Product Image ?>
<p class="short-description-action" style="display: inline-block;">
    <?php $image = $_helperAction->getImage($block)?>
    <img class="action-image-photo" style="width:<?= $wight ?>; height: <?= $height ?>; float: left;
            margin: 7px 7px 7px 0;" src="<?= $image ?>"/>
    <?= $block->getShortDescription() ?>
</p>

<div class="products wrapper grid products-grid">
    <ol class="products grid items product-items">
        <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
        <?php foreach ($_productCollection as $_product) : ?>
            <li class="item product product-item">
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, 'category_page_grid');
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                       class="product photo product-item-photo"
                       tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= $block->escapeUrl($_product->getProductUrl()) ?>">
                                <?= /* @noEscape */
                                $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </strong>
                        <?= /* @noEscape */
                        $block->getProductPrice($_product) ?>
                        <?= $block->getProductDetailsHtml($_product) ?>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
    </ol>
</div>
