<?php

/**
 * @var \Puga\Action\Block\Action $block
 */

$blocks = $block->getActionCollection();
$wight = '200px';
$height = '200px';
?>
<h1><?= _('Action') ?></h1>
<?php foreach ($blocks as $key => $item) : ?>
    <div style="display: flow-root;">
        <div class="right" style="float: right !important;">
            <div id="end-date">
                <?php if ($item->getEndDatetime()) : ?>
                    <div class="time-left"
                         style="width: 175px; background-color: #F9F9F9; font-weight: bold; text-align: center;">
                        <h3 style="font-size: 12px; color: rgb(89, 89, 89);">До завершення акції</h3>
                        <div class="unit-container"
                             style="text-align: center; margin-top: -2px; display: inline-block; color: rgb(227, 24, 55)">
                            <?php $date = $block->getDate($item); ?>
                            <?= $date ?>
                            <p class="unit"
                               style="clear: both; margin-top: -7px; font-size: 11px;">
                                <?= __('Днів') ?></p>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        </div>
        <h2>
            <a href="<?= $block->getUrl('puga_action/view/action/', ['id' => $item->getId()]); ?>"
               style="color: #568da7; font-size: 18px;">
                <?= $item->getName(); ?>
            </a>
        </h2>
        <p class="short-description-action">
            <img class="action-image-photo" src="<?= $block->getImage($item) ?>"
                 style="width:<?= $wight ?>; height: <?= $height ?>; float: left;
                         margin: 7px 7px 7px 0;"/>
            <?= $item->getDescription() ?>
        </p>
    </div>
<?php endforeach; ?>
