<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Puga\Action\Block\Product\Action $block */

$collection = $block->getCollection();
$_helper = $this->helper(Puga\Action\Helper\Data::class);
$wight = '100px';
$height = '100px';
?>
<div id="product-review-container" data-role="product-review"></div>
<?= $block->getChildHtml() ?>
<?php foreach ($collection as $key => $action) : ?>
    <div style="display: flow-root;">
        <div class="right" style="float: right !important;">
            <div id="end-date">
                <?php if ($action->getEndDatetime()) : ?>
                    <div class="time-left"
                         style="width: 175px; background-color: #F9F9F9; font-weight: bold; text-align: center;">
                        <h3 style="font-size: 12px; color: rgb(89, 89, 89);">До завершення акції</h3>
                        <div class="unit-container"
                             style="text-align: center; margin-top: -2px; display: inline-block; color: rgb(227, 24, 55)">
                            <?php $date = $_helper->getDate($action); ?>
                            <?= $date ?>
                            <p class="unit"
                               style="clear: both; margin-top: -7px; font-size: 11px;">
                                <?= __('Днів') ?></p>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        </div>
        <h2>
            <a href="<?= $block->getUrl('puga_action/view/action/', ['id' => $action->getId()]); ?>"
               style="color: #568da7; font-size: 18px;">
                <?= $action->getName(); ?>
            </a>
        </h2>
        <p class="short-description-action">
            <img class="action-image-photo" src="<?= $_helper->getImage($action) ?>"
                 style="width:<?= $wight ?>; height: <?= $height ?>; float: left;
                         margin: 7px 7px 7px 0;"/>
            <?= $action->getDescription() ?>
        </p>
    </div>
<?php endforeach; ?>


